name: Pages

on:
  pull_request:
  workflow_dispatch:
  

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # git-restore-mtime-bare uses the ref log to find the correct timestamp
          # for each file. This requires a full git history. The default value (1)
          # creates a shallow checkout.
          fetch-depth: 0
      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Use Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.1'
      
      - name: generate config
        run: go run ./genconfig/main.go --env=gh-pages > _config.yml

      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Use Node.js 16.6.0
        uses: actions/setup-node@v1
        with:
          node-version: '16.6.0'
      
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying branch